apiVersion: v1
kind: Service
metadata:
  name: finalprojectcode-service
  namespace: default
spec:
  selector:
    app: finalprojectcode
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
